<?php
/**
 * SclContact (https://github.com/SCLInternet/SclContact)
 *
 * @link https://github.com/SCLInternet/SclContact for the canonical source repository
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */

namespace SclContact\Options;

/**
 * Interface for options class for this module.
 *
 * @author Tom Oram <tom@scl.co.uk>
 */
interface ContactOptionsInterface
{
    /**
     * Set the name of the country manager service to use.
     *
     * @param  string $manager
     * @return self
     */
    public function setCountryManager($manager);

    /**
     * Return the name of the country manager service.
     *
     * @return string
     */
    public function getCountryManager();

    /**
     * Set the name of the country class to use.
     *
     * @param  string $class
     * @return self
     */
    public function setCountryClass($class);

    /**
     * Get the name fo the country class to be used.
     *
     * @return string
     */
    public function getCountryClass();

    /**
     * Set if the countries generated by the country manager should be shared.
     *
     * @param  boolean $shared
     * @return self
     */
    public function setSharedCountries($shared);

    /**
     * Are the countries returned from the country manager shared.
     *
     * @return boolean
     */
    public function getSharedCountries();

    /**
     * Set the identifier for the default country to display.
     *
     * @param  mixed $countryIdentifier
     * @return self
     */
    public function setDefaultCountry($countryIdentifier);

    /**
     * Return the identifier for the default country to be displayed.
     *
     * @return mixed
     */
    public function getDefaultCountry();

    /**
     * Set the path to the config file for the built in country manager.
     *
     * @param  string $path
     * @return self
     */
    public function setCountryFilePath($path);

    /**
     * Get the path to the config file for the built in country manager.
     *
     * @return self
     */
    public function getCountryFilePath();
}
